[project]
name = "micrograd"
version = "0.1.0"
description = "autograd library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pytest>=8.4.1",
    "seaborn>=0.13.2",
]
